### ISSUE TITLE
Сдача тестового

### ISSUE THREAD

**Issue by sxkxixx** [axon-expert/backend-test-task#4]
Здравствуйте. Подскажите как сдать выполненное тестовое?

**Comment by sxkxixx** [comment]
@hirotasoshu

**Comment by hirotasoshu** [comment]
> Здравствуйте. Подскажите как сдать выполненное тестовое?

Вообще надо было рекрутеру отправить, но я уже сам вижу ваш репозиторий, так что добавлю в очередь на проверку)
